platform:ios ,'6.0'
pod 'UIColor-Utilities', '~> 1'
pod 'GoogleAnalytics-iOS-SDK', '~> 3'
pod 'ReactiveCocoa','~> 2'
pod 'libextobjc', '~> 0.4'
pod 'HockeySDK', '~>3'
pod 'CargoBay', '~>2'
pod 'RMStore', '~>0.4'
pod 'MagicalRecord', '~>2'
pod 'MNCalendarView', '~>0.0.1'
pod 'PDTSimpleCalendar', '~>0.7'
pod 'OCCalendar-Ext', '~>0.1'
pod 'DSLCalendarView', '~>0.0.1'
pod 'MBCalendarKit', '~>2.0.0'
pod 'RDVCalendarView', '~>1.0.7'